### ISSUE TITLE
Typos in Digital Accelerator / Workshop Day One slides PDF file

### ISSUE THREAD

**Issue by oghaffari** [18F/digitalaccelerator#1]
Just a few things I noticed as I read through this. Some of these may not be errors, but intentional - apologies in advance if they were meant to be!

Edit: by this, I mean the first day's workshop slides, found here:

Online: https://pages.18f.gov/digitalaccelerator/assets/workshop-day-one.pdf
Github: https://github.com/18F/digitalaccelerator/blob/18f-pages/assets/workshop-day-one.pdf

---

Slide 8 (About Proto-Personas), left column (Proto-personas are:), first bullet: the **_to_** is missing. "A variation of personas used **_to_** develop early design hypotheses"

Slide 16 (Step 3: Character refinement), left column (body of text), first line: the **_a_** is missing. "As **_a_** group, discuss key attributes that are important [...]"

Slide 17 (Step 4: Combine information into proto-personas), left column, first line (note: this is more an assumption on my part rather than a grammar/spelling issue considering we were to select 5 prioritized proto-personas): proto-persona is singular rather than plural. "For prioritized proto-persona**_s_**, fill out key information [...]" Also, another assumption, but I think the following part would read better with a comma between user and such. "fill out key information about the user**_,_** such as name, age, goals & objectives [...]"

Slide 28 (Finding Problem and Solution Fit), left column (bullet points), third bullet (All products...): There are two hyphens between segments and it's. Not sure if that was intentional or not.

Slide 35 (Methods Introduction), right column (5 Ws and H), third bullet (Use when...): Some was used instead of **_something_**. "Use when you're creating some**_thing_** new from nothing [...]"

**Comment by atrain440** [comment]
Hi oghaffari! Thanks for pointing out the typos! We'll post this to the site this week. Gold star!

**Comment by oghaffari** [comment]
No problem, I appreciate the kind words! Keep up the great work!
